package com.qaware.mentoring.bean.validation;

/**
 * Generated by IntellJ (Refactor -> Replace Contructor with Builder)
 */
public class AddressBuilder {

    private String number;
    private String street;
    private String city;
    private String state;
    private String zip;
    private String country;

    public AddressBuilder setNumber(String number) {
        this.number = number;
        return this;
    }

    public AddressBuilder setStreet(String street) {
        this.street = street;
        return this;
    }

    public AddressBuilder setCity(String city) {
        this.city = city;
        return this;
    }

    public AddressBuilder setState(String state) {
        this.state = state;
        return this;
    }

    public AddressBuilder setZip(String zip) {
        this.zip = zip;
        return this;
    }

    public AddressBuilder setCountry(String country) {
        this.country = country;
        return this;
    }

    public Address createAddress() {
        return new Address(number, street, city, state, zip, country);
    }
}