package com.qaware.mentoring.spring.data.repositories;

import com.qaware.mentoring.spring.data.entity.Person;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

/**
 * Spring Data repository, implementation generated by Spring.
 */
@Repository
public interface PersonRepository extends JpaRepository<Person, Long> {
}
